version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      - NODE_ENV=development
    restart: unless-stopped
