version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: auroraphtgrp/chatbot-uniko-llm
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped